# Generated by Django 3.1.3 on 2021-06-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=256, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='상품가격')),
                ('category', models.TextField(verbose_name='상품카테고리')),
                ('product_url', models.TextField(verbose_name='상품링크')),
            ],
        ),
    ]
