# Generated by Django 3.1.3 on 2021-06-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
