# Generated by Django 3.1.3 on 2021-06-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_m',
            name='product_number',
            field=models.IntegerField(default=1),
        ),
    ]
