# Generated by Django 3.1.3 on 2021-06-21 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_prod_m_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_m',
            name='product_number',
        ),
    ]
